config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'access#menu'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'programs/score', :to => 'programs#score'

  resources :admin_users do
     member do
      get :delete
     end
  end

  resources :programs do
     member do
      get :delete
     end
  end

  resources :lines, :only => [:edit,:update]

  resources :tests, :only => [:index,:edit,:update]

end

app/models/program.rb
class Program < ApplicationRecord

	has_many :lines, :dependent => :destroy
	has_many :tests, :dependent => :destroy

	scope :sorted, lambda {order("position")}
	scope :visible, lambda{where(:visible => true)}
	
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  before_action :confirm_logged_in
  before_action :is_superuser

  # READ ACTIONS
  def index
    @programs = Program.sorted
  end
  
  def show
    @program = Program.find(params[:id])
    @lines = @program.lines
  end

  def score
    @program_name = Program.find(params[:format]).name
    @program = params[:format]
    @users = AdminUser.where("id IN (SELECT \"tests\".admin_user_id FROM \"tests\" WHERE (program_id=#{@program}))").sorted
  end

  # CREATE ACTIONS
  def new
    @program = Program.new
  end

  def create
    @program = Program.new(:name=> params[:program][:name],:position => params[:program][:position],:source => params[:program][:source], :visible => params[:program][:visible], :addressing => params[:program][:addressing])
      if @program.save
      Sic.pass1(@program.source)
      Sic.pass2(@program.id)
      File.open("object_program.txt").each do |line|
        temp = line.split("^")
        temp.delete("")
        line = temp.join("^")
        @program.object_program +=  line
      end
      @program.save
      flash[:success] = "Program created successfully."
      redirect_to(programs_path)
    else
      flash[:danger].now = "Program error."
      render 'new'
    end
  end

  # UPDATE ACTIONS
  def edit
    @program = Program.find(params[:id])
  end

  def update
    @program = Program.find(params[:id])
    if @program.update_attributes(program_params)
      redirect_to (edit_line_path)
    else
      render 'edit'
    end
  end

  # DELETE ACTIONS
  def delete
    @program=Program.find(params[:id])
  end

  def destroy
    @program=Program.find(params[:id])
    @program.destroy
    flash[:success] = "Program '#{@program.name}' deleted successfully."
    redirect_to(programs_path)
  end

private

  def program_params
    params.require(:program).permit(:name,:position,:visible,:addressing,:source)
  end

end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/delete.html.erb
<% @page_title = "Delete Test"%>
<%= form_for(@program,:method => 'delete') do |f| %>
<div class="center page-header">
  <h2>Delete <%= f.object.name %>?</h2>
</div>
    <div class="center form-group">
      <p>Are you sure you wish to permanently delete this?</p>
      <div class="col-sm-12">
        <%= f.submit "Delete Test",class: 'btn btn-danger btn-lg' %>
      </div>
    </div>
<% end %>

app/views/programs/edit.html.erb
<% @page_title = "Create Test"%>
<div class="center page-header">
  <h2>Edit Test</h2>
</div>
	<%= form_for(@program,:url=> program_path(@program),:method => 'patch', :html => {:class => 'form-horizontal', :role => 'form'}) do |f| %>
    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name of test', autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :position, class: 'col-sm-2 control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :position, class: 'form-control', placeholder: 'Position in list', autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :addressing, class: 'col-sm-2 control-label' %>
      <div class="col-sm-8">
        <%= f.radio_button :addressing, 'true', autofocus: true %>Yes
        <%= f.radio_button :addressing, 'false', autofocus: true %>No
      </div>
    </div>
    <div class="form-group">
      <%= f.label :visible, class: 'col-sm-2 control-label' %>
      <div class="col-sm-8">
        <%= f.radio_button :visible, 'true', autofocus: true %>Yes
        <%= f.radio_button :visible, 'false', autofocus: true %>No
      </div>
    </div>
    <div class="form-group">
      <%= f.label :source, class: 'col-sm-2 control-label' %>
      <div class="col-sm-8">
        <%= f.text_area :source, class: 'form-control', placeholder: 'Write source assembly code here', autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :object_program, class: 'col-sm-2 control-label' %>
      <div class="col-sm-8">
        <%= f.text_area :object_program, rows: "7", class: 'form-control', placeholder: 'Write source assembly code here', autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Next",class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
	<% end %>

app/views/programs/index.html.erb
<% @page_title = "Manage Tests" %>
<div class="center page-header">
  <h2>Manage Tests</h2>
  <%= link_to "Add new Test", new_program_path, :class => 'btn btn-primary' %>
</div>
<% @programs.each do |program| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="program-title">
            <%= program.name %>
          </div>
          <div class="program-body">
            <%= link_to("Scoreboard", programs_score_path(program), :class => 'btn btn-primary') %>
            <%= link_to("Show", program_path(program), :class => 'btn btn-info') %>
            <%= link_to("Edit", edit_program_path(program), :class => 'btn btn-info') %>
            <%= link_to("Delete", delete_program_path(program), :class => 'btn btn-danger') %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/programs/new.html.erb
<% @page_title = "Create Test" %>
<div class="center page-header">
  <h2>Create Test</h2>
</div>
	<%= form_for(@program, :url=> programs_path, :method => 'post', :html => {:class => 'form-horizontal', :role => 'form'} ) do |f| %>
      <div class="form-group">
        <%= f.label :name, class: 'col-sm-2 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Name of test', autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :position, class: 'col-sm-2 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :position, class: 'form-control', placeholder: 'Position in list', autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :addressing, class: 'col-sm-2 control-label' %>
        <div class="col-sm-8">
          <%= f.radio_button :addressing, 'true', autofocus: true %>Yes
          <%= f.radio_button :addressing, 'false', autofocus: true %>No
        </div>
      </div>
      <div class="form-group">
        <%= f.label :visible, class: 'col-sm-2 control-label' %>
        <div class="col-sm-8">
          <%= f.radio_button :visible, 'true', autofocus: true %>Yes
          <%= f.radio_button :visible, 'false', autofocus: true %>No
        </div>
      </div>
    <div class="form-group">
      <%= f.label :source, class: 'col-sm-2 control-label' %>
      <div class="col-sm-8">
        <%= f.text_area :source, class: 'form-control', placeholder: 'Write source assembly code here', autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Create Test", class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
	<% end %>

app/views/programs/score.html.erb
<% @page_title = "Scoreboard"%>
<div class="center page-header">
  <h2>Scoreboard for [<%= @program_name %>]</h2>
</div>
<div class="well col-xs-8 col-xs-offset-2">
  <table class="table table-bordered table-striped table-hover table-condensed" >
    <th>Year</th>
    <th>Section</th>
    <th>Roll number</th>
    <th>Name</th>
    <th>Email</th>
    <th>Username</th>
    <th>Percentage Score</th>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.year %></td>
          <td><%= user.section %></td>
          <td><%= user.roll_number %></td>
          <td><%= user.name %></td>
          <td><%= mail_to(user.email) %></td>
          <td><%= user.username %></td>
          <% test = Test.where("program_id=#{@program} and admin_user_id=#{user.id}").first %>
          <td><%= test.score %></td>
        </tr>
    <% end %>
  </table>
</div>

app/views/programs/show.html.erb
<div class="center page-header">
  <h2>Show [<%= @program.name %>]</h2>
</div>
<div class="well col-xs-8 col-xs-offset-2">
  <table class="table table-bordered table-striped table-hover table-condensed">
    <th class="success text-center">Address</th>
    <th class="success text-center">Program</th>
    <th class="success text-center">Object Code</th>
    <% @lines.each do |line| %>
        <tr>
          <td class="active data"> <%= line.address %> </td>
          <td class="active data"> <%= line.data %> </td>
          <td class="info text-center object-code"> <%= line.code %> </td>
        </tr>
    <% end %>
  </table>
</div>