config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'access#menu'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'programs/score', :to => 'programs#score'

  resources :admin_users do
     member do
      get :delete
     end
  end

  resources :programs do
     member do
      get :delete
     end
  end

  resources :lines, :only => [:edit,:update]

  resources :tests, :only => [:index,:edit,:update]

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

	before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]
	before_action :is_superuser, :except => [:login, :attempt_login, :logout]

	def menu
		@username = session[:username]
		redirect_to(programs_path)
	end

	def login
	end

	def attempt_login
		if params[:username].present? && params[:password].present?
			found_user = AdminUser.where(:username => params[:username]).first
			if found_user
				authorized_user = found_user.authenticate(params[:password])
			end
		end

		if authorized_user
			session[:user_id] = authorized_user.id
			session[:username] = authorized_user.username
			redirect_to(admin_path)
		else
			flash.now[:danger] = "Invalid username or password."
			render('login')
		end
	end

	def logout
		session[:user_id] = nil
		session[:username] = nil
		flash[:success] = 'You are logged out.'
		redirect_to(access_login_path)
	end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/login.html.erb
<div class="center jumbotron">
  <h1>Welcome!</h1>
  <%= form_tag(access_attempt_login_path, :method => :post, :class => 'form-horizontal', :role => 'form' ) do %>
      <div class="form-group">
        <%= label_tag(:username, nil, class: 'col-sm-2 control-label') %>
        <div class="col-sm-8">
          <%= text_field_tag(:username, params[:username], :class => 'form-control', :placeholder => 'Enter Username') %>
        </div>
      </div>
      <div class="form-group">
        <br>
        <%= label_tag(:password, nil, class: 'col-sm-2 control-label') %>
        <div class="col-sm-8">
          <%= password_field_tag(:password, nil, :class => 'form-control', :placeholder => 'Enter Password') %>
        </div>
      </div>
      <br/>
      <div class="form-group">
        <div class="col-sm-6">
          <%= submit_tag("Login", :class => 'btn btn-danger btn-lg')  %>
        </div>
      </div>
  <% end %>
</div>