config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'access#menu'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'programs/score', :to => 'programs#score'

  resources :admin_users do
     member do
      get :delete
     end
  end

  resources :programs do
     member do
      get :delete
     end
  end

  resources :lines, :only => [:edit,:update]

  resources :tests, :only => [:index,:edit,:update]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

	has_secure_password
	has_many :tests, :dependent => :destroy

	scope :sorted, lambda {order('superuser DESC, year DESC,section, roll_number, first_name, last_name')}

	def name
		"#{first_name} #{last_name}"
	end
	
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

	before_action :confirm_logged_in
	before_action :is_superuser

	def index
		@admin_users = AdminUser.sorted
	end

	def show
		@admin_user = AdminUser.find(params[:id])
		@tests = @admin_user.tests.order('updated_at DESC')
	end

	def new
		@admin_user = AdminUser.new
	end

	def create
		@admin_user = AdminUser.new(admin_user_params)
		if @admin_user.save
			flash[:success] = 'User created successfully.'
			redirect_to(admin_users_path)
		else
			render('new')
		end
	end

	def edit
		@admin_user = AdminUser.find(params[:id])
	end

	def update
		@admin_user = AdminUser.find(params[:id])
		if @admin_user.update_attributes(admin_user_params)
			flash[:success] = 'User updated successfully.'
			redirect_to(admin_users_path)
		else
			render('edit')
		end
	end

	def delete
		@admin_user = AdminUser.find(params[:id])
	end

	def destroy
		@admin_user = AdminUser.find(params[:id])
		@admin_user.destroy
		flash[:success] = 'User destroyed successfully.'
		redirect_to(admin_users_path)
	end

	private

	def admin_user_params
		params.require(:admin_user).permit(
				:first_name,
				:last_name,
				:section,
				:roll_number,
				:year,
				:email,
				:username,
				:password,
				:superuser
			)
	end

end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/_form.html.erb
<div class="form-group">
  <%= f.label :year, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :year, class: 'form-control', placeholder: 'Year of user', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :section, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :section, class: 'form-control', placeholder: 'Section of user', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :roll_number, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :roll_number, class: 'form-control', placeholder: 'Roll no. of user', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :first_name, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :first_name, class: 'form-control', placeholder: 'First name of user', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :last_name, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last name of user', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :email, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :email, class: 'form-control', placeholder: 'Email of user', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :username, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :username, class: 'form-control', placeholder: 'Username for user (required)', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :password, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :password, class: 'form-control', placeholder: 'Password for user (required for new users)', autofocus: true %>
  </div>
</div>
<div class="form-group">
  <%= f.label :superuser, class: 'col-sm-2 control-label' %>
  <div class="col-sm-8">
    <%= f.radio_button :superuser, 'true', autofocus: true %>Yes
    <%= f.radio_button :superuser, 'false', autofocus: true %>No
  </div>
</div>

app/views/admin_users/delete.html.erb
<% @page_title = "Delete User"%>
<%= form_for(@admin_user,:method => 'delete') do |f| %>
    <div class="center page-header">
      <h2>Delete [<%= f.object.username %>]?</h2>
    </div>
    <div class="center form-group">
      <p>Are you sure you want to delete this user?</p>
      <div class="col-sm-12">
        <%= f.submit "Delete User",class: 'btn btn-danger btn-lg' %>
      </div>
    </div>
<% end %>

app/views/admin_users/edit.html.erb
<% @page_title = "Update User"%>
<div class="center page-header">
  <h2>Edit User</h2>
</div>
<%= form_for @admin_user, html: { class: 'form-horizontal', role: 'form' } do |f| %>
		<%= render(:partial => 'form', :locals => {:f => f}) %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Update User",class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
<% end %>

app/views/admin_users/index.html.erb
<% @page_title = "Manage Users" %>
<div class="center page-header">
  <h2>Manage Users</h2>
  <%= pluralize(@admin_users.size, 'user') %> found
  <div class="center">
    <%= link_to("Add User", new_admin_user_path, :class => 'btn btn-primary') %>
  </div>
</div>
<div>
  <table class="table table-bordered table-striped table-hover table-condensed">
    <tr>
      <th>Year</th>
      <th>Section</th>
      <th>Roll number</th>
      <th>Name</th>
      <th>Email</th>
      <th>Username</th>
      <th>Admin</th>
      <th>Actions</th>
    </tr>
    <% @admin_users.each do |admin_user| %>
        <tr>
          <td><%= admin_user.year %></td>
          <td><%= admin_user.section %></td>
          <td><%= admin_user.roll_number %></td>
          <td><%= admin_user.name %></td>
          <td><%= mail_to(admin_user.email) %></td>
          <td><%= admin_user.username %></td>
          <td><%= admin_user.superuser ? 'Yes' : 'No' %></td>
          <td>
            <%= link_to('Scorecard', admin_user_path(admin_user), :class => 'btn btn-primary btn-sm') %>
            <%= link_to('Edit', edit_admin_user_path(admin_user), :class => 'btn btn-info btn-sm') %>
            <%= link_to('Delete', delete_admin_user_path(admin_user), :class => 'btn btn-danger btn-sm') %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/admin_users/new.html.erb
<% @page_title = "Create User"%>
<div class="center page-header">
  <h2>Create User</h2>
</div>
<%= form_for @admin_user, html: { class: 'form-horizontal', role: 'form' } do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Create User",class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
<% end %>

app/views/admin_users/show.html.erb
<% @page_title = "Scorecard"%>
<div class="center page-header">
  <h2>Scorecard for [<%= @admin_user.username %>]</h2>
</div>
<div class="well col-xs-8 col-xs-offset-2">
	<table class="table table-bordered table-striped table-hover table-condensed">
		<th class="success text-center">Test Date</th>
		<th class="success text-center">Name</th>
		<th class="success text-center">Percentage Score</th>
		<% @tests.each do |test| %>
		<tr>
			<td class="active data"> <%= test.updated_at %> </td>
			<td class="active data"> <%= test.program.name %> </td>
			<td class="info text-center object-code"> <%= test.score %> </td>
		</tr>
		<% end %>
	</table>
</div>