config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'access#menu'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'programs/score', :to => 'programs#score'

  resources :admin_users do
     member do
      get :delete
     end
  end

  resources :programs do
     member do
      get :delete
     end
  end

  resources :lines, :only => [:edit,:update]

  resources :tests, :only => [:index,:edit,:update]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright &copy Rajat Pundir
  </small>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %> alert-dismissible" role="alert">
          <a href="#" class="close" data-dismiss="alert" aria-label="Close">&#215;</a>
          <%= msg %>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Assembler", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <% if is_logged_in %>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <% if user.superuser? %>
              <ul class="nav navbar-nav">
                <li><%= link_to "Manage Users", admin_users_path %></li>
                <li><%= link_to "Manage Tests", programs_path %></li>
              </ul>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <% if user.superuser? %>
                <li><%= link_to "Take Test", tests_path %></li>
            <% else %>
                <li><%= link_to user.name, tests_path %></li>
            <% end %>
            <li><%= link_to "Logout", access_logout_path %></li>
          </ul>
        </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= @page_title || "Assembler" %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
<% user = AdminUser.where(:username => session[:username]).first %>
<% if user %>
    <%= render 'layouts/navigation', :is_logged_in => true, :user => user %>
<% else %>
    <%= render 'layouts/navigation', :is_logged_in => false %>
<% end %>
<%= render 'layouts/messages' %>
<div class="container">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>